image: node:8

stages:
  - pre
  - test
  - build
  - publish
  - post

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - cd functions
  - npm install

create:merge-request:
  image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-mr
  stage: pre
  before_script: []
  variables:
    REMOVE_BRANCH_AFTER_MERGE: "true"
    SQUASH: "true"
    AUTO_MERGE: "true"
    TARGET_BRANCH: "master"
    COMMIT_PREFIX: "WIP"
    USE_ISSUE_NAME: "true"
    DESCRIPTION: ".gitlab/merge_request/merge_request.md"
  except:
    - master
    - tags
  script:
    - gitlab_auto_mr

lint:
  stage: test
  script:
    - npm run lint

lint:code-formatter:
  stage: test
  script:
    - npm run code-formatter-check

lint:compiler:
  stage: test
  script:
    - npm run compiler-check

tests:unit:
  stage: test
  script:
    - npm run tests

test:coverage:
  stage: test
  only:
    - master
  script:
    - npm run coverage
  coverage: '/^All files\s+\|\s+\d+\.*\d*\s+\|\s*(\d+\.*\d*)/'

publish:firebase:functions:
  stage: publish
  only:
    - /^release/.*$/
  script:
    - npm run deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_TOKEN

publish:firebase:env:
  stage: publish
  only:
    - /^release/.*$/
  script:
    - npm run firebase functions:config:set env.production=true --non-interactive --token $FIREBASE_DEPLOY_TOKEN

publish:release:
  image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-release
  stage: post
  only:
    - /^release/.*$/
  before_script: []
  variables:
    DESCRIPTION: "This was auto-generated by the gitlab-auto-release tool, https://gitlab.com/gitlab-automation-toolkit/gitlab-auto-release."
    CHANGELOG: CHANGELOG.md
  script:
    - gitlab_auto_release --link-assets false
