image: node:8

stages:
  - pre
  - test
  - build
  - publish
  - post

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - cd functions
  - yarn

create:merge-request:
  image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-mr
  stage: pre
  before_script: []
  except:
    - master
    - tags
  script:
    - gitlab_auto_mr -t master -c WIP -d ./.gitlab/merge_request/merge_request.md -r -s --use-issue-name

lint:
  stage: test
  script:
    - yarn run lint

lint:code-formatter:
  stage: test
  script:
    - yarn run code-formatter-check

lint:compiler:
  stage: test
  script:
    - yarn run compiler-check

tests:unit:
  stage: test
  script:
    - yarn run tests

test:coverage:
  stage: test
  only:
    - master
  script:
    - yarn run coverage
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

publish:firebase:functions:
  stage: publish
  only:
    - /^release/.*$/
  script:
    - yarn run deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_TOKEN

publish:firebase:env:
  stage: publish
  only:
    - /^release/.*$/
  script:
    - yarn firebase functions:config:set env.production=true --non-interactive --token $FIREBASE_DEPLOY_TOKEN

publish:release:
  image: registry.gitlab.com/gitlab-automation-toolkit/gitlab-auto-release
  stage: post
  only:
    - /^release/.*$/
  before_script: []
  variables:
    GIT_STRATEGY: none
  script:
    - gitlab_auto_release -c CHANGELOG.md -d "This was auto-generated by the gitlab-auto-release tool, https://gitlab.com/gitlab-automation-toolkit/gitlab-auto-release."
